name: Deploy projeto Node + React

on:
  push:
    branches:
      - master
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repositório
        uses: actions/checkout@v3

      # ===============================
      # BACKEND
      # ===============================

      - name: Setup Node.js (backend)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # - name: Cache npm (backend)
      #   uses: actions/cache@v3
      #   with:
      #     path: backend/node_modules
      #     key: ${{ runner.os }}-node-${{ hashFiles('backend/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-

      - name: Instalar dependências backend
        working-directory: backend/
        run: npm install

      - name: Testar backend
        working-directory: backend/
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: npx jest



      - name: Docker Login
        if: github.ref == 'refs/heads/prod'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

     

      - name: Build e Push Docker image BACKEND
        if: github.ref == 'refs/heads/prod'
        uses: docker/build-push-action@v5
        with:
          context: backend/
          platforms: linux/amd64
          push: true
          tags: |
            timbeck97/loja-backend:latest
            timbeck97/loja-backend:${{ github.run_number }}


      # ===============================
      # FRONTEND
      # ===============================

      - name: Setup Node.js (frontend)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache npm (frontend)
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Instalar dependências frontend
        working-directory: frontend/
        run: npm install

      - name: Testar frontend
        working-directory: frontend/
        run: npm test -- --watchAll=false
        
      - name: Build frontend
        working-directory: frontend/
        run: npm run build

      - name: Docker Login
        if: github.ref == 'refs/heads/prod'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e Push Docker image FRONTEND
        if: github.ref == 'refs/heads/prod'
        uses: docker/build-push-action@v5
        with:
          context: frontend/
          push: true
          tags: |
            timbeck97/loja-frontend:latest
            timbeck97/loja-frontend:${{ github.run_number }}
