name: Deploy projeto Node + React

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Setup Node.js (backend)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache npm (backend)
        uses: actions/cache@v3
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Instalar dependências backend
        working-directory: backend/
        run: npm install

      - name: Testar backend
        working-directory: backend/
        run: npm test --if-present

      # Docker Login
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build e Push da imagem do backend
      - name: Build e Push Docker image BACKEND
        uses: docker/build-push-action@v5
        with:
          context: backend/
          push: true
          cache-from: type=registry,ref=timbeck97/loja-backend:cache
          cache-to: type=registry,ref=timbeck97/loja-backend:cache,mode=max
          tags: timbeck97/loja-backend:latest, timbeck97/loja-backend:${{ github.run_number }}

      # ===============================
      # FRONTEND - React
      # ===============================
      # - name: Setup Node.js (frontend)
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18

      # - name: Cache npm (frontend)
      #   uses: actions/cache@v3
      #   with:
      #     path: frontend/node_modules
      #     key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-

      # - name: Instalar dependências frontend
      #   working-directory: frontend/
      #   run: npm install

      # - name: Build frontend
      #   working-directory: frontend/
      #   run: npm run build

      # - name: Build e Push Docker image FRONTEND
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: frontend/
      #     push: true
      #     cache-from: type=registry,ref=timbeck1997/loja-frontend:cache
      #     cache-to: type=registry,ref=timbeck1997/loja-frontend:cache,mode=max
      #     tags: timbeck1997/loja-frontend:latest, timbeck1997/loja-frontend:${{ github.run_number }}

